string firstName;
firstName = "Bob";
string firstName;
"Bob" = firstName;
int firstName;
firstName = "Bob";
string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
firstName = "Liem";
Console.WriteLine(firstName);
firstName = "Isabella";
Console.WriteLine(firstName);
firstName = "Yasmin";
Console.WriteLine(firstName);
string firstName;
Console.WriteLine(firstName);
string firstName = "Bob";
Console.WriteLine(firstName);
var message = "Hello world!";
var message = "Hello world!";
var message = "Hello World!";
string name = "Bob";
int messages = 3;
decimal temperature = 34.4m;
Console.Write("Hello, ");
Console.Write(name);
Console.Write("! You have ");
Console.Write(messages);
Console.Write(" messages in your inbox. The temperature is ");
Console.Write(temperature);
Console.Write(" celsius.");
